Description: >
    Carlos Rivas / Udacity 2019

Parameters:

    ProjectName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
Resources:

  IAMRoleWebApp:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  IAMWebAppS3IP:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - Ref: 'IAMRoleWebApp'

Outputs:

  IAMRoleWebApp:
    Description: 'Allow EC2 instances to manage Web App S3'
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${ProjectName}-IAM-NAME